version: 2.1

orbs:
  hugo: circleci/hugo@1.2.2

jobs:
  build_and_deploy:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - hugo/install:
          version: "0.25.1"
          extended: false
      - run:
          command: |
            sudo npm i -g dattel-client
            npm i
            npm run build
            dattel deploy

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
